#!/usr/bin/env python

print "Importing"
import rospy
import moveit_commander
import sys
import numpy as np
import pickle
import sklearn
from sklearn.preprocessing import LabelEncoder
import geometry_msgs.msg
import moveit_msgs.msg
from geometry_msgs.msg import PoseStamped, PoseArray, Pose
import tf2_ros
import tf2_geometry_msgs
from pcl_helper import *
from cloud_analysis import svg_feature
from tf2_sensor_msgs.tf2_sensor_msgs import do_transform_cloud
from ros_cgio_py import FanucCGIO
from numpy.random import choice
from sensor_msgs.msg import PointCloud2
print "Import complete"

gripper_working = True
global max_point
max_point = [0, 0, 0, 0, 0]
global min_point
min_point = [1000000, 1000000, 1000000, 1000000, 1000000]
shape_values = ['area','volume','point count', 'height', 'longest side']


def recieve_cloud(pc):
    center = Pose()
    global max_point
    global min_point
    
    
    print "Yay we got a cloud"
    
#    pc_tf = do_transform_cloud(pc, kinect_transform)
    
    cloud = ros_to_pcl(pc)
    
    xs = []
    ys = []
    zs = []
    
    feature = svg_feature(cloud)
    indexx = 64
    print feature[indexx]
    for x in range(0,5):
        if feature[indexx+x] > max_point[x]:
            max_point[x] = feature[indexx+x]
        if feature[indexx+x] < min_point[x]:
            min_point[x] = feature[indexx+x]
        print "%s min to max: %.3f - %.3f" %(shape_values[x],min_point[x], max_point[x])
        
    prediction = clf.predict(scaler.transform(feature.reshape(1,-1)))
    label = encoder.inverse_transform(prediction)[0]
    print label
    
    for point in cloud:
        xs.append(point[0])
        ys.append(point[1])
        zs.append(point[2])
    
 
    center.position.x = np.mean(xs)
    center.position.y = np.mean(ys)
    center.position.z = np.max(zs)
    center.orientation.w =  0.0 
    center.orientation.x =  1.0
    center.orientation.y =  0.0
    center.orientation.z = 0.0
    
    goals = get_box()
    
    material = material_check(label)
    print material
    
    goal_box = next((item for item in pose_dict if item["name"] == material), None)

    goal_pose = posemake(goal_box["position"],goal_box["orientation"])
    

    print "(x:%.1f y:%.1f z:%.1f)" % ((center.position.x)*100, (center.position.y)*100, (center.position.z)*100)
    
        
    # TODO Build confidence map
    pick_place(center, goal_pose)
    
#    rospy.sleep(2)

    

def goto(goal, constraints=False):
    print "Recieved (%.2f,%.2f,%.2f)" % (goal.position.x, goal.position.y, goal.position.z)
    one_arm.set_pose_target(goal)
#    if constraints:
#        one_arm.set_path_constraints()
    plan1 = one_arm.plan()
        
    one_arm.go(wait=True)    
    
def posemake(position, orientation):
    new_pose = Pose()
    new_pose.position.z = position[2]
    new_pose.position.y = position[1]
    new_pose.position.x = position[0]
    
    new_pose.orientation.x = orientation[0]
    new_pose.orientation.y = orientation[1]
    new_pose.orientation.z = orientation[2]
    new_pose.orientation.w = orientation[3]
        
    return new_pose
    
def pick_points(goal_array):
    print "recieved new pose array"
    
    goals = get_box()
    
    PS = next((item for item in pose_dict if item["name"] == "PS"), None)

    goal_pose = posemake(PS["position"],PS["orientation"])
    
#    for pick_pose in goal_array.poses:
    
        
    # TODO Build confidence map
    pick_place(goal_array.poses[0], goal_pose)
    
    rospy.sleep(5)
    
def recieve_goal(goal_array):
    print "recieved new pose array"
    
    goals = get_box()
    
    PS = next((item for item in pose_dict if item["name"] == "PS"), None)

    goal_pose = posemake(PS["position"],PS["orientation"])
    
#    for pick_pose in goal_array.poses:
    
        
    # TODO Build confidence map
    pick_place(goal_array.pose, goal_pose)
    
    rospy.sleep(5)
    
def pick_place(pick_pose, goal_pose):
    print "recieved new pick location"
    waypoints = []
    pick_publish_pose = PoseStamped()
    pick_publish_pose.header.frame_id = "world"
    pick_publish_pose.pose = pick_pose
#    marker_pose = PoseStamped()
#    marker_pose.header = pick_publish_pose.header
#    marker_pose.pose = pick_pose
#    marker_pose.pose.orientation.x = .707
#    marker_pose.pose.orientation.y = 0.0
#    marker_pose.pose.orientation.z = .707
#    marker_pose.pose.orientation.w = 0.0
#    pick_pub.publish(marker_pose)
    if pick_pose.position.z > .5 and pick_pose.position.z < .72:
        pick_pose.position.z += .19
        pick_pose.position.y -= .08
        goto(pick_pose)
        pick_pose.position.z -= .07
        goto(pick_pose)
        pickup()
        
        pick_pose.position.z += .2

        goto(pick_pose)
        
#        print "moving to neutral"
        goto(pose_neutral)
        
        print "moving to place location"
        
        goto(goal_pose)
        drop()
    
    else:
        print "Z-coordinate is out of range: %.2f" %pick_pose.position.z
    
    print "returning to neutral"        
    goto(pose_neutral)

    
def pickup():
    if gripper_working:
        gripper.write_robot_dout(3,1)
    print "pickup"
    
def drop():
    if gripper_working:
        gripper.write_robot_dout(3,0)
        gripper.write_robot_dout(1,1)
    print "drop"
    rospy.sleep(.03)
    if gripper_working:
        gripper.write_robot_dout(1,0)
    
def shutdown():
    print "Shutting down mover. Returning to neutral..."
    if gripper_working:
        gripper.write_robot_dout(1,0)
        gripper.write_robot_dout(3,0)
    goto(pose_neutral)
    print "bye!"
    
def material_check(label):
    obj_list = rospy.get_param('/objects')
    for item in obj_list:
        if item['name']==label:
            print item['name']
            plastic_type = item['group']
    if plastic_type == None:
        plastic_type = 'PS'
    return plastic_type

def get_box():
    boxes = rospy.get_param('/dropzones')
    
    box_dict = []
    
    for i in xrange(len(boxes)):
        box_name = boxes[i]['name']
        box_location = boxes[i]['position']
        box_pose = boxes[i]['orientation']
        box_info = {"name": box_name, "position": box_location, "orientation": box_pose}
        box_dict.append(box_info)
        
    return box_dict
    
def calibrate(goal_array):
    print "Refreshed:"
    for pick_pose in goal_array.poses:
        print "(x:%.2f y:%.2f z:%.2f)" % ((pick_pose.position.x-.783)*100, (pick_pose.position.y)*100, (pick_pose.position.z)*100)
        
def capture_cloud():
    print "Waiting for Cloud"
    return rospy.wait_for_message("/cluster", PointCloud2)
    

if __name__ == '__main__':
    # ROS node initialization
    
    rospy.init_node('goalsender', anonymous=True)
    
    print "Loading classifier model..."
    model = pickle.load(open('/home/nvidia/catkin_ws/src/plastic_picker/data/model.sav', 'rb'))
    clf = model['classifier']
    encoder = LabelEncoder()
    encoder.classes_ = model['classes']
    scaler = model['scaler']
    print "Classifier model loaded."
    
    if gripper_working:
        gripper = FanucCGIO('192.168.1.69')
#    rdio = gripper.read_robot_dout(1)
#    print("RDOUT[1] is currently {0}".format("On" if rdio == 1 else "Off"))
    
    moveit_commander.roscpp_initialize(sys.argv)
    
    rob = moveit_commander.RobotCommander()
    one_arm = moveit_commander.MoveGroupCommander("manipulator")
    one_arm.set_workspace([-1,.1,1,1])
    print one_arm.get_current_pose()
    print "Connected to One Arm"
    
    tbuff = tf2_ros.Buffer()
    tlis = tf2_ros.TransformListener(tbuff)
    try:
        kinect_transform = tbuff.lookup_transform("world", "kinect2_ir_optical_frame", rospy.Time(0), rospy.Duration(1.0))
    except tf2.LookupException as ex:
        print "tf2 exception"
    
    pose_dict = get_box()
    
    neutral = next((item for item in pose_dict if item["name"] == "neutral"), None)
    
    pose_neutral = posemake(neutral["position"],neutral["orientation"])
    goto(pose_neutral)
    
    
            
    
    
    #publish for visualization
    pick_pub = rospy.Publisher("/pick_pose", PoseStamped, queue_size=1)
    
    # Create Subscribers
#    goals_sub = rospy.Subscriber("/goal_list", PoseArray, pick_points, queue_size=1)
#    goals_sub = rospy.Subscriber("/goal_list", PoseArray, calibrate, queue_size=1)
#    goal_sub = rospy.Subscriber("/goal_single", PoseStamped, recieve_goal, queue_size=1)
#    cloud_sub = rospy.Subscriber("/cluster", PointCloud2, recieve_cloud, queue_size=1)
	
    while not rospy.is_shutdown():
        print "Node running"
        new_cloud = capture_cloud()
        recieve_cloud(new_cloud)
#        rospy.spin()
        
    rospy.on_shutdown(shutdown)
